### ISSUE TITLE
outdated version numbers

### ISSUE THREAD

**Issue by jkensik** [WraithM/haskoin-bitcoind#4]
![Screenshot from 2019-12-20 17-29-33](https://user-images.githubusercontent.com/40124613/71298924-1da61180-2350-11ea-9322-87e7a1a17de6.png)

**Comment by wraithm** [comment]
Okay, I've pushed http://hackage.haskell.org/package/network-bitcoin-1.9.1 and http://hackage.haskell.org/package/haskoin-bitcoind-0.4.1 to hackage.
